/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Adjustment (
  /* The type of adjustment represented by this Adjustment.  | **Type**              | **Description** | | --------------------- | --------------------------------------------------------- | | chargeback            | Chargeback (debits merchant's account, credits the customer's account). | | chargeback-reversal   | Reverses a previous chargeback (credits merchant's account, debits the customer's account).| | misc-credit           | Credit's the merchant's account. | | misc-debit            | Debits's the merchant's account. | | float                 | Weird thing no one uses          |  */
  adjustmentType: AdjustmentEnums.AdjustmentType,
  /* Date and time, in [RFC-3339](https://tools.ietf.org/html/rfc3339) timestamp format, when this adjustment was applied to the merchant's account.  */
  adjustmentDate: DateTime,
  /* Absolute value of the amount of this adjustment. This should reflect the amount that was submitted on the clearing file. This value should NOT reflect any applied fees or discounts.  */
  adjustmentAmount: Double,
  /* Uniquely identifies this Transaction within Vyze's settlement system.  While the `settlement_id` is optional for adjustments.  It is HIGHLY recommended the lender include it if at all possible as it helpful for reporting and audit purposes.  */
  settlementId: Option[String],
  /* Customer Account Number that is being credited or debited for the transaction. Some adjustments might not directly impact a customer account, hence this field is optional for adjustments.  */
  customerAccountNumber: Option[String],
  /* Lender-defined code that categorizes the reason for this adjustment.  */
  adjustmentCode: Option[String],
  /* A concise explanation of this adjustment.  */
  adjustmentDescription: String
) extends ApiModel

object AdjustmentEnums {

  type AdjustmentType = AdjustmentType.Value
  object AdjustmentType extends Enumeration {
    val Chargeback = Value("chargeback")
    val `Chargeback-reversal` = Value("chargeback-reversal")
    val `Misc-credit` = Value("misc-credit")
    val `Misc-debit` = Value("misc-debit")
    val Float = Value("float")
  }

}

